#!/bin/bash
set -o xtrace
echo "post merge hook run"
echo "status"
git status
echo "diff"
git diff-tree -r --no-commit-id ORIG_HEAD HEAD
echo "var"
changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"
echo "$changed_files"

check_run() {
  echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

check_run models/jw-core "cd apps/harnessw && npm -v && cd - && cd apps/spa && npm -v && cd -"
check_run models/naan "cd apps/harness && npm -v && cd - && cd apps/spa && npm -v && cd -"
check_run models/masala-lib "cd apps/masala-console && npm -v && cd - && cd apps/masala-server && npm -v && cd -"